// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PMZ_Core","status":true,"description":"Pokemon MZ Essential - Core System","parameters":{"maxPartySize":"6","boxCount":"24","boxSize":"30","battleMovesLimit":"4","encounterRate":"15"}},
{"name":"PMZ_Battle","status":true,"description":"Pokemon MZ Essential - Battle & Capture System","parameters":{}},
{"name":"PMZ_Menu","status":true,"description":"Pokemon MZ Essential - Party Menu System","parameters":{}}
];
